name: Health check

on:
  push:
    branches:
      - main
  #schedule:
  #  - cron: '5 * * * *' 


jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Perfrom health check
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-lv2o.onrender.com
          max-attempts: 3
          retry-delay: 5s