name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: 
      - opened
      - synchronize

env:
  SKIP_DEPLOY_TAG: ${{ contains( join(github.event.commits.*.message), '#skip' ) }}
  DEPLOY_URL: 'https://full-stack-open-pokedex-lv2o.onrender.com'

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build project
        run: npm run build
      - name: Test project
        run: npm test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: e2e tests
        run: npm run test:e2e
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && env.SKIP_DEPLOY_TAG == 'false' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Build failure
        env:
          COMMIT_URL: ${{ github.event.head_commit.url }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.committer.username }}
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with: 
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: Build failed
          details: "Build failed for commit $COMMIT_URL by author $COMMIT_AUTHOR"
          
    
  tag_release:
    needs: 
      - simple_deployment_pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Tag
        id: step_generate_tag
        if: ${{ github.event_name == 'push' && env.SKIP_DEPLOY_TAG == 'false' }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          DRY_RUN: false
      - name: Deploy success notification
        if: ${{ github.event_name == 'push' && env.SKIP_DEPLOY_TAG == 'false' }}
        env: 
          NEW_TAG: ${{ steps.step_generate_tag.outputs.tag }}
        uses: rjstone/discord-webhook-notify@v1
        with: 
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          text: A new version $NEW_TAG successfully deployed.
          description: "URL: ${{ env.DEPLOY_URL }} by ${{ github.triggering_actor }}"    

